apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: kkv2
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: yolean/kkv2
    custom:
      buildCommand: >-
        mvn
        clean
        package
        -Dquarkus.container-image.build=true
      dependencies:
        paths:
        - "**/*"
        ignore:
        - target/**
deploy:
  kubectl:
    manifests:
    - ./k8s/kkv.yaml