apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: kkv2
build:
  local:
    push: false
  tagPolicy:
    sha256: {}
  artifacts:
  - image: yolean/kkv2
    custom:
      buildCommand: >-
        mvn
        clean
        package
        -Dquarkus.container-image.build=true
        -DskipTests=true
      dependencies:
        paths:
        - "**/*"
        ignore:
        - target/**
deploy:
  kustomize:
    paths:
    - "./k8s"

profiles:
- name: prod-build
  patches:
  - op: replace
    path: /build/artifacts/0/custom/buildCommand
    value: >-
      ( mvn
      clean
      package
      -Pnative
      -Djib.allowInsecureRegistries=true
      -Dquarkus.container-image.push=true
      )
