quarkus:
  #container-image:
    #build: true
    #image: yolean/kkv2
  tls:
    trust-all: true
  rest-client:
    text-response-service:
      url: http://kkv-test-client-headful-service.kkv.svc.cluster.local:3000
  
  #jib:
  #  base-jvm-image: ${IMAGE_BASE_JRE:eclipse-temurin:17-jre-alpine}


kafka:
  bootstrap:
    servers: one-node-cluster.kkv.svc.cluster.local:9092

mp:
  messaging:
    incoming:
      config: 
        connector: smallrye-kafka
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        auto:
          offset:
            reset: earliest
        consumer-rebalance-listener:
          name: config.rebalancer