quarkus:
  container-image:
    build: true
    image: yolean/kkv2
  tls:
    trust-all: true
  jib:
    #platforms: linux/arm64/v8
    platforms: linux/amd64


"%dev":
  quarkus:
    kafka:
      devservices:
        enabled: true
        #image: vectorized/redpanda:latest
        #port: 9092
    
"%prod":
  kafka:
    bootstrap:
      servers: one-node-cluster.kkv.svc.cluster.local:9092

mp:
  messaging:
    incoming:
      config: 
        connector: smallrye-kafka
        value:
          deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        auto:
          offset:
            reset: earliest
        consumer-rebalance-listener:
          name: config.rebalancer

se:
  yolean:
    client-proxy/mp-rest/scope: javax.inject.Singleton

httpClient:
  target:
    port: 3000