quarkus:
  container-image:
    build: true
    image: yolean/kkv2
  tls:
    trust-all: true
  jib:
    #platforms: linux/arm64/v8
    platforms: linux/amd64
  
"%dev":
  kafka:
    devservices:
      enabled: true
    
"%prod":
  kafka:
    bootstrap:
      # servers: kafka-v2-write-bootstrap:9092
      servers: one-node-cluster.kkv.svc.cluster.local:9092


mp:
  messaging:
    incoming:
      ${KAFKA_INCOMING_TOPIC}:
      #config: 
        connector: smallrye-kafka
        value:
          deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        auto:
          offset:
            reset: earliest
        consumer-rebalance-listener:
          name: config.rebalancer
        #group:
        #  id: site-${YOLEANSITE_ID}_events-v1-backend

kkv:
  namespace: ${YOLEANSITE_ID}
  #namespace: kkv
  target:
    port: ${QUARKUS_HTTP_PORT}
  endpointslice:
    name: kkv-test-client-bvr9r
    # Should this be the label selector of the service instead?