quarkus:
  container-image:
    build: true
    image: ${IMAGE:yolean/kkv2}
    push: ${IMAGE_PUSH:false}
    insecure: ${IMAGE_PUSH_INSECURE:false}
  tls:
    trust-all: ${IMAGE_PUSH_TRUST_ALL:false}
  jib:
    #platforms: linux/arm64/v8
    platforms: linux/amd64

mp:
  messaging:
    incoming:
      config:
        topic: ${KAFKA_INCOMING_TOPIC}
        bootstrap:
          servers: ${KAFKA_BOOTSTRAP_SERVERS}
        connector: smallrye-kafka
        value:
          deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        auto:
          offset:
            reset: ${KAFKA_OFFSET_RESET:earliest}
        consumer-rebalance-listener:
          name: config.rebalancer
        #group:
        #  id: site-${YOLEANSITE_ID}_events-v1-backend

kkv:
  target:
    service:
      name: ${TARGET_SERVICE_NAME}
      port: ${TARGET_SERVICE_PORT:8080}

"%test":
  mp:
    messaging:
      incoming:
        config:
          topic: ${KAFKA_INCOMING_TOPIC:kkv-test-topic}
          bootstrap:
            servers: ""
  kkv:
    target:
      service:
        name: kkv-test-service
