apiVersion: apps/v1
kind: Deployment
metadata:
  name: kkv2
  labels:
    app: kkv2
spec:
  selector:
    matchLabels:
      app: kkv2
  replicas: 1
  template:
    metadata:
      name: kkv2
      labels:
        app: kkv2
    spec:
      containers:
        - name: kkv2
          image: yolean/kkv2
          ports:
            - containerPort: 8080
          env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: one-node-cluster.kkv.svc.cluster.local:9092
          #- name: kafka_group_id
          #  value: kkvdemo-testtopic
          - name: KAFKA_INCOMING_TOPIC
            value: config
          - name: KAFKA_OFFSET_RESET
            value: earliest
          - name: TARGET_SERVICE_NAME
            value: kkv-test-client
          - name: TARGET_SERVICE_PORT
            value: "3000"
      serviceAccountName: kkv-v2