---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kkv2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kkv2
  labels:
    app: kkv2
spec:
  selector:
    matchLabels:
      app: kkv2
  replicas: 1
  template:
    metadata:
      name: kkv2
      labels:
        app: kkv2
    spec:
      containers:
        - name: kkv2
          image: yolean/kkv2
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
      serviceAccountName: kkv2
---
apiVersion: v1
kind: Service
metadata:
  name: kkv2
  labels:
    app: kkv2
spec:
  ports:
    - port: 8080
      name: http
  type: LoadBalancer
  selector:
    app: kkv2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podlister
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podlister
subjects:
- kind: ServiceAccount
  name: kkv2
  namespace: kkv
roleRef:
  kind: ClusterRole
  name: podlister
  apiGroup: rbac.authorization.k8s.io