apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: endpoins-watcher-rolebinding
subjects:
  - kind: ServiceAccount
    name: kkv-v2
roleRef:
  kind: Role
  name: endpoints-watcher
  apiGroup: rbac.authorization.k8s.io